meta_title: "ComingUp>> l'actu à venir"
meta_description: "Prenez un temps d'avance sur l'actualité"
meta_image: "background.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
